### ISSUE TITLE
Error updating cache

### ISSUE THREAD

**Issue by sbrl** [pepa65/tldr-bash-client#1]
When I run `tldr --cache`, I get this:

```
[/tmp/tmp.efhXYFsvHL/pages.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp.efhXYFsvHL/pages.zip or
        /tmp/tmp.efhXYFsvHL/pages.zip.zip, and cannot find /tmp/tmp.efhXYFsvHL/pages.zip.ZIP, period.
mv: cannot stat '/tmp/tmp.efhXYFsvHL/pages/*': No such file or directory

 Pages cached in /home/sbrl/.local/share/tldr
```

**Comment by pepa65** [comment]
Thanks for reporting! It seems there is now a permanent redirect in place for the cache archive, that wasn't handled well. I updated the client to version 0.31

**Comment by sbrl** [comment]
Thanks! :smiley_cat:

**Comment by sbrl** [comment]
Yep, that's solved the problem! Perhaps you could create a new GitHUb release for it? I'm not sure hwo forks work in that regard.

**Comment by pepa65** [comment]
I updated the version number and made a new tag, that's all I know in the way of creating a release. Anybody installing from master will automatically get the latest anyway, so it's pretty rolling.
