### ISSUE TITLE
Less prompt not showing percentage

### ISSUE THREAD

**Issue by Susensio** [pepa65/tldr-bash-client#10]
In running tldr in raspbian and less fails to show the percentage in prompt. Problem located in line 339
```
trap 'less -Gg -~RXQFP"%pB\% tldr $I$page$XI - browse up/down, press Q to exit" <<<"$stdout"' EXIT
```
I have been tinkering with other prompt variables instead of `%pB` and less fail to show both *size in bytes* and *total line count*.

When I scroll all way down, It gets both values right and percentage works properly, but this is mostly useless as I already know where the end of file is.

I know TLDR pages are pretty slim and this feature ir rarely used, but I'm curious about why it is failing.

**Comment by pepa65** [comment]
I would guess it is something about how the terminal is set up. What terminal are you using? What happens when you use other terminals?
What happens if you view any other file with less, can you get it to show percentages properly??

**Comment by Susensio** [comment]
I'm using bash on raspbian stretch (raspberry pi).
Other files do show percentages properly.

**Comment by pepa65** [comment]
Where do you run bash? Is it through an ssh session, or on the console, or on a terminal in a graphical environment?

**Comment by Susensio** [comment]
I've tried in:
Raspberry pi 3 terminal, in the graphical enviroment
Also ssh to raspberry pi zero w and cli.
I will investigate further to give you more information.

**Comment by Susensio** [comment]
I've just checked in Ubuntu 14.04.5 LTS and the problem persists.
If I enter command `tldr tar` in bash the statusbar shows:
`?% tldr tar - browse up/down, press Q to exit`

**Comment by pepa65** [comment]
I think this is not something I can fix as I think it is a problem of less. What can be done is adapt the less prompt, or even not use less at all. What I could do is make the less prompts more accessible for modification, by assigning them to variables early in the script. What do you say?
