### ISSUE TITLE
Cache not downloaded

### ISSUE THREAD

**Issue by borekb** [pepa65/tldr-bash-client#12]
From an empty installation, running `tldr -u` produces an empty directory, only with `index.json` file. Details:

```
$ rm -rf ~/.local/share/tldr
$ tldr -u

 Pages cached in /c/Users/Borek/.local/share/tldr

 Pages cached in /c/Users/Borek/.local/share/tldr

# (yes, twice)

$ find ~/.local/share/tldr
/c/Users/Borek/.local/share/tldr
/c/Users/Borek/.local/share/tldr/index.json
```

I thought this would download a copy of `tldr-pages/tldr` files. I saw instances where `tldr <something>` didn't work:

```
$ tldr tldr

 Could not download page /c/Users/Borek/.local/share/tldr/common/tldr.md with /mingw64/bin/curl -sLfo

 tldr page for command tldr not found
```

Any ideas?

**Comment by borekb** [comment]
Unzipping is problematic:

https://github.com/pepa65/tldr-bash-client/blob/73a49fb016bb0fe21b33c282a689554994e1e11a/tldr#L383

It produces just this for me (in a simulated environment where I downloaded `pages.zip` to `.`):

```
$ unzip pages.zip -d . 'pages/*'
Archive:  pages.zip
   creating: ./pages/
  inflating: ./pages/index.json
```

This seems to fix it for me (note the other asterisk):

```
$ unzip pages.zip -d . 'pages/**'
```

Will test some more and submit a PR..

**Comment by pepa65** [comment]
I followed your recipe and on Linux this all works OK...

**Comment by pepa65** [comment]
This is fixed in 0.40 -- on Gitlab...

**Comment by borekb** [comment]
Are you moving due to the Microsoft acquisition or something else? I personally find it a bit unfortunate but of course it's entirely your choice.

**Comment by pepa65** [comment]
It is unfortunate, because Github is where most of the action is... Gitlab works just the same, but has fewer users.

**Comment by borekb** [comment]
And are you moving because of the acquisition or for different reasons? I'm just curious as GitLabs seems like quite an aggressive startup to me).

**Comment by pepa65** [comment]
Definitely because of the Microsoft acquisition. Gitlab has a better "Free software" reputation, I haven't heard that they are aggressive, what gives you that impression?

**Comment by borekb** [comment]
I'm building a startup myself (in an open source space, _slightly_ comparable in model but of course not in scale at all) so can see "hints" of a typical startup aggressiveness in some of their moves – mostly around acquiring new users or pushing new features at the expense of stability, sometimes. They are trying, no denying of that, but GitHub (and also Microsoft) have demonstrated over long periods of time that they are really good stewards of collaborative open source development; GitLab feels to me more about pushing features and acquiring users.

Note: I am personally not happy at all about the acquisition. I think that GitHub was a unique jewel in our industry, with an amazing balance of a product, community, stability of the service, support, ecosystem, everything. That will be impossible to improve, IMO, but I also relatively trust that Microsoft realizes that.

**Comment by pepa65** [comment]
Right now, Gitlab is not a happening place, haven't interacted there with anyone... But moving away from Github is a matter of principle. I think I will keep the repo's here but include a message in the readme, so people know where to find more up-to-date versions.

**Comment by borekb** [comment]
How about pushing to here from time to time as well? For example, if someone installed your script via Antigen, they would not know about the move and would stop receiving updates.

**Comment by pepa65** [comment]
I am not familiar with Antigen, does it not work with Gitlab?

**Comment by borekb** [comment]
I have your script installed via:

```
antigen bundle pepa65/tldr-bash-client
```

This assumes GitHub. I think that you can use full URL for other services but in any way, it means manually updating `.zshrc` (after realizing that the project moved).

**Comment by pepa65** [comment]
I would hope antigen will start supporting other repo's more easily. If it was really easy, I might push to this repo to support antigen. But I don't know an easy way. (And it would go against the pull to encourage more people to diversify away from Github.)

**Comment by borekb** [comment]
I think an occasional `git push github-origin master`  should be enough, the collaboration can be on GitLab. But I might be an exception here, maybe most people download your script directly.

**Comment by pepa65** [comment]
When I do `git push http://github.com/pepa65/tldr-bash-client origin master` I get:
```
warning: redirecting to https://github.com/pepa65/tldr-bash-client/
fatal: refs/remotes/origin/HEAD cannot be resolved to branch.
```

**Comment by borekb** [comment]
Do you have your remote setup correctly? Plain HTTP doesn't seem correct at all.

**Comment by pepa65** [comment]
My remote is obviously Gitlab... WIth https it's the same.

**Comment by borekb** [comment]
I assume you have multiple remotes -- one for GitLab (probably your `origin`) and another one for GitHub (like `github-origin`). The message looks like you're not on a branch, you could try `git checkout master`.

**Comment by pepa65** [comment]
I am now mirrorring to github as wel for now.
