### ISSUE TITLE
No tldr pages found

### ISSUE THREAD

**Issue by sbrl** [pepa65/tldr-bash-client#14]
Hello!

Long-time tldr-bash-client user here, and also tldr-pages maintainer :D

I woke up today to find that your client is no longer working. I see this error:

```bash
$ tldr tar
/home/sbrl/bin/tldr: line 251: /home/sbrl/.local/share/tldr/pages/index.json: No such file or directory

 Pages cached in /home/sbrl/.local/share/tldr

 tldr page for command tar not found

 Contribute new pages at: https://github.com/tldr-pages/tldr
```

I think something's happened to `index.json`. Any clues as to what's gone wrong?

**Comment by mebeim** [comment]
Relevant issue I opened a while ago on the GitLab repo: https://gitlab.com/pepa65/tldr-bash-client/-/issues/13

[This PR ](https://gitlab.com/pepa65/tldr-bash-client/-/merge_requests/13/diffs?commit_id=2c48fb80d413b83b83f5e21814757b277315b016) by @MasterOdin should solve the issue.

**Comment by pepa65** [comment]
Thanks for the heads-up! It seems that index.json is no longer under each `pages` directory... This means the archive has changed format at some point. Anyway, should be fixed now.

**Comment by pepa65** [comment]
@mebeim Very strange, I never seem to have gotten any notification from Gitlab about your issue. Indeed, the change is fairly simple.

**Comment by mebeim** [comment]
@pepa65 it's something we decided [a long time ago](https://github.com/tldr-pages/tldr/issues/2865), but only recently changed (see [relevant PR](https://github.com/tldr-pages/tldr/pull/5063)). I did not know you had a GitHub repository at the time so I only opened the issue on GitLab. Thanks for the quick fix though! 🙂
