### ISSUE TITLE
Download website offline?

### ISSUE THREAD

**Issue by niklasmohrin** [pepa65/tldr-bash-client#16]
The installation instructions do not work, when trying to download the client, nothing happens:

```shell
$ curl -v https://4e4.win/tldr
*   Trying 99.83.154.118:443...
```

**Comment by pepa65** [comment]
Sorry, for some reason this didn't get pushed to github. I had to let 4e4.win go, too expensive to renew. It can now be downloaded at https://good4.eu/tldr

**Comment by niklasmohrin** [comment]
I am curious: Any reason against just using https://raw.githubusercontent.com/pepa65/tldr-bash-client/master/tldr?

**Comment by pepa65** [comment]
As you are probably aware, good4.eu/tldr redirects to the URL you mention, so that could be used. When I just want to quickly get the binary, I use the shortened version, easier to remember, and shorter to type. Either works of course.
