### ISSUE TITLE
以中文用户(zh)出现“Description doesn't end in full stop.”问题的原因以及解决办法

### ISSUE THREAD

**Issue by LiuZengqiang** [pepa65/tldr-bash-client#18]
使用简中 pages.zh 会出现"Description doesn't end in full stop"报错，这是因为中文使用“。”作为句子的结尾，而下载的脚本中会检查是否以"."为结尾，如果不以"."为结尾就会报错。
因此解决的办法有两个：
* 一是将``~/.local/share/tldr/`` 下用 ``pages/`` 代替 ``pages.zh/``
* 或者将从``good4.eu/tldr``下载的脚本中将其中的``[[ ! ${REPLY: -1} = '.' ]] && Unlinted "Description doesn't end in full stop"`` 修改为``[[ ! ${REPLY: -1} = '.' ]] && [[ ! ${REPLY: -1} = '。' ]] && Unlinted "Description doesn't end in full stop"``

**Comment by pepa65** [comment]
Not sure if the Chinese full stop is incorporated in the official `tldr` spec, but I have made the accommodation. Thank you for opening this issue!

**Comment by pepa65** [comment]
When doing for instance `LANG=zh tldr tar` I discovered that `less` didn't properly render Chinese, I had to set something like LC_ALL to have UTF-8.

Another issue was in the `bash` handling of the final character in a UTF-8 string that includes a Newline (0x0A) byte: it didn't recognize/honour the full UTF-8 character, so I needed to strip the Newline before proper processing,

**Comment by LiuZengqiang** [comment]
After the modification (version 0.6.0), the results cannot be rendered with color in either zh or other languages :(
You can try it in your shell. I believe that changing "。" to "." in the tldr master repository is the way to solve this problem once and for all.

**Comment by LiuZengqiang** [comment]
The command ``LANG=zh tldr tar`` did not properly render Chinese, but `LANG=zh_CN.UTF-8`` is successful.

**Comment by pepa65** [comment]
Sorry, my fault for not testing properly. I fixed it a different way.
I do not have rights to the master repo, but I think this works now. (v0.6.1)
