### ISSUE TITLE
Blank Space

### ISSUE THREAD

**Issue by UndarkAido** [pepa65/tldr-bash-client#2]
Is there any way to make this not print a bunch of empty newlines to fill the terminal? I can see the appeal, but it's rather annoying to me.

**Comment by pepa65** [comment]
If you edit the appearance, just delete any occurrences of `Newline` in the configuration. In the current version (0.31) lines 19, 21, 34 and 35.

**Comment by pepa65** [comment]
Thanks for your question. This was the reason for my rewrite, to make adapting the appearance of the output easier! 👍

**Comment by UndarkAido** [comment]
Awesome, thank you!

**Comment by UndarkAido** [comment]
Oh wait, that's not what I meant. Here's how to see what I mean: maximize the terminal, and run `tldr` for any command. What I want is for tldr not to make all the blank space between its output and the terminal lines before and after. Here:
I want this:
```
$ tldr bash












 bash
 Bourne-Again SHell.
 `sh`-compatible command line interpreter.

 Start interactive shell:
 bash

 Execute a command:
 bash -c "command"

 Run commands from a file:
 bash file.sh

 Run commands from STDIN:
 bash -s

 Print the version information of bash (use `echo $BASH_VERSION` to show just the version string):
 bash --version













```
To be this:
```
$ tldr bash
 bash
 Bourne-Again SHell.
 `sh`-compatible command line interpreter.

 Start interactive shell:
 bash

 Execute a command:
 bash -c "command"

 Run commands from a file:
 bash file.sh

 Run commands from STDIN:
 bash -s

 Print the version information of bash (use `echo $BASH_VERSION` to show just the version string):
 bash --version
```

**Comment by pepa65** [comment]
Thanks for reminding me of what annoyed me as well..!
I think I found the fix, see version 0.32

**Comment by UndarkAido** [comment]
Ok, cool! I'll check it out in a bit.

**Comment by UndarkAido** [comment]
Perfect! :+1:

**Comment by borekb** [comment]
I'm on v0.39 but still see the blank lines, as @Aidoboy in https://github.com/pepa65/tldr-bash-client/issues/2#issuecomment-304917157.

I just installed via `antigen bundle pepa65/tldr-bash-client`, no custom configuration.

**Comment by pepa65** [comment]
The problem is, that `less` doesn't behave exactly the same, also depending on the version and terminal used. If you don't want to use `less` at all, then you can set `TLDR_LESS=0` in your shell (like, put `export TLDR_LESS=0` into your `~/.bashrc`, or just edit the `tldr` binary to set it).

Or you can experiment what commandline options to `less` make your issue go away. If you find any, please let me know!

**Comment by borekb** [comment]
🤦‍♂️  I even tried the `TLDR_LESS=0` before but forgot the `export` keyword. Thanks.

(BTW, this is the first time I see that `less` would be problematic. I'm in MSYS2 shell on Windows, that is true, but all other things work with `less` correctly. In my terminal, the whitespace is like in `less` but I'm returned to the main prompt immediately, like if `cat` was used.)

**Comment by pepa65** [comment]
The problem with `less` is more once starting to use all kinds of esoteric options, see lines 200 and 336.

**Comment by borekb** [comment]
Wondering if they are necessary 😄

**Comment by pepa65** [comment]
I just see what you mean (I think...). It is because line 336 was changed from `-Gg` to `+Gg`. In issue #11 this was changed because the percentage starts out unknown otherwise.
