### ISSUE TITLE
How to turn off automatic updates?

### ISSUE THREAD

**Issue by LiuZengqiang** [pepa65/tldr-bash-client#20]
How to turn off automatic updates?
In some network environments, it is difficulty to download the tldr.zip.
How to turn off automatic updates?

**Comment by pepa65** [comment]
Use the environment variable TLDR_EXPIRY which can be set in this line (line 39 in version 0.6.2): `: ${TLDR_EXPIRY:=7}` -- change the 7 into a higher number, like 365 (only refresh pages older than a year). You can also just set this variable in the environment, like: `export TLDR_EXPIRY=999` which you can put in your `~/.bashrc` file.

Of course, you need to download the tldr.zip at least once..!

**Comment by LiuZengqiang** [comment]
Thanks.
