### ISSUE TITLE
Support the new windows platform

### ISSUE THREAD

**Issue by sbrl** [pepa65/tldr-bash-client#6]
We've recently added a new platform: `windows`. Support for it in this client would be awesome :smile_cat:

**Comment by pepa65** [comment]
What would be needed to support it?

**Comment by sbrl** [comment]
Hrm. Looks like lines [#381](https://github.com/pepa65/tldr-bash-client/blob/master/tldr#L381) and #417 need updating, but I'm not sure that's everything.

**Comment by pepa65** [comment]
OK, sorry, I totally didn't get that..! So now windows is a platform..? Does it have man pages as well? Or are we going to pollute tldr with all kinds of DOS commands..?!

**Comment by sbrl** [comment]
Thanks for fixing this! :D

Yep, windows is now a platform apparently. No, it doesn't natively have man pages. All windows-specific commands are going to stay inside the `windows` platform folder.
