### ISSUE TITLE
Sublicensing removed original copyright notice

### ISSUE THREAD

**Issue by ehashman** [pepa65/tldr-bash-client#7]
In 8394083faa23a5ff4dd7d303d7367ab1a414e174 the project was sublicensed GPLv3, but the original copyright notice was removed (in violation of the terms of the original MIT license). That license/copyright notice should be restored to the source tree to ensure attribution is still given to the original author and compliance with the original license is maintained :)

**Comment by pepa65** [comment]
Done in e241a2f.
